### ISSUE TITLE
Error transcribing audio

### ISSUE THREAD

**Issue by fskhri** [ardha27/AI-Waifu-Vtuber#1]
Traceback (most recent call last):
  File "C:\Users\Administrator\AI-Waifu-Vtuber\run.py", line 141, in <module>
    record_audio()
  File "C:\Users\Administrator\AI-Waifu-Vtuber\run.py", line 54, in record_audio
    transcribe_audio("input.wav")
  File "C:\Users\Administrator\AI-Waifu-Vtuber\run.py", line 63, in transcribe_audio
    chat_raw = transcript.text
               ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'transcript' where it is not associated with a value

ada solusi ga bg?

**Comment by ardha27** [comment]
Aku sempet error gitu juga, kalo ga salah cuma tak run ulang trus bisa lagi. Dugaanku sih koneksi internet. Atau karena input.wav nya kosong/kamu ga ngomong apa apa

**Comment by fskhri** [comment]
udh saya isi suara, tapi masih aja error bg

**Comment by ardha27** [comment]
Coba variabel transcript ditulis dulu diatas

def transcribe_audio(audio_file):
    transcript = "" # initialize transcript to an empty string
    # transcription code here
    chat_raw = transcript.text
    # rest of the code here

**Comment by fskhri** [comment]
masih tetep error bg, saya tunggu next update aja dah wkwkwk

**Comment by fskhri** [comment]
kalo bisa jangan pake openAI bg, soal nya token nya udh ga bisa lagi

**Comment by ardha27** [comment]
API dari OpenAInya udah kamu isi belum? Itu harus pake API akun OpenAI mu

**Comment by fskhri** [comment]
sudah, tapi kan sekarang openAI bayar jadi ada tulisan openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.

tapi kemarin ku coba buat via youtube bisa kok  👍

**Comment by fskhri** [comment]
tinggal via mic nya aja yang engga bisa

**Comment by ardha27** [comment]
masih nyoba engga gan? udah kubuatin requirements.txt nya, mungkin membantu

**Comment by fskhri** [comment]
Masih saya coba kok bg :)

**Comment by ardha27** [comment]
di line ini
if c.author.isChatOwner or c.author.name == 'Nightbot':
hapus "c.author.isChatOwner"

line itu artinya : apabila chatter adalah owner atau nightbot maka abaikan

**Comment by fskhri** [comment]
ok 👍

**Comment by fskhri** [comment]
udah ku ikutin requirements.txt nya dan work mic sama youtube chat nya 😁
