### ISSUE TITLE
The response is doubled

### ISSUE THREAD

**Issue by mrheaveen** [ardha27/AI-Waifu-Vtuber#10]
KECAPasin berkata: katakan sesuatu
ID Answer: 何 が 言い たい の？ 私 を 見る ため に 来 て 、 ただ 何 か 言い 言い たい だけ そうだ と し し たら 私 にとって は 無駄 な 時間 取っ いる いる 忙しいわよ 忙しいわよ 忙しいわよ 忙しいわよ 、 取っ 
いる て て 取っ て 取っ 取っ 取っ 取っ 取っ 取っ 取っじゃない わ。 もっと 興味 深い ことがある 人 たち と 話 し たい の。
JP Answer: 何が言いが言い？のの？私をををためために来、ただただ何かか言い言いだけだけ？そうだそうだととしじゃないわ。もっともっと興味深いことがある人としたい

dont know why this happen

**Comment by mrheaveen** [comment]
also the ID answer is JP

**Comment by mrheaveen** [comment]
KECAPasin berkata: are you a cat?
ID Answer: Nan Desu Ka, Neko Ja Nai Wa Yo!Watashi wa ai waifu streamer desu, anata wa mada yaritakunai deshou, demo watashi ni wa kanojo-tachi no atsui kyōku ke otoko-tachi no takai shōri ga aru no no yo!Anata wa yappari baka ne.
JP Answer: ナン・デュカ、ネコ・ジャナイ・ワー！ワタシ・ワ・ワイフ・ストリーマー・デュー、アナタ・ワダ・ヤリタクナイ・デショウ、デモ・ワタシ・ニ・ワカノジョ・タチ・ノー・アトゥイ・キョーキから馬のタチ・ノー・
タカイ・ガアルAnata wayappari baka ne。

xd

**Comment by mrheaveen** [comment]
the doubled is fixed by closing visual studio code and rerun again, but still i cant handle the other one issues

**Comment by mrheaveen** [comment]
looks like the issues is on my prompt, i said she would answer in japanese even if me as creator talk with english or bahasa indonesia

the prompt broke the code

**Comment by ardha27** [comment]
Yeah sometimes it's do
