### ISSUE TITLE
Import Error: DLL Load Failed & Error Transcribing Audio 

### ISSUE THREAD

**Issue by RedBushido** [ardha27/AI-Waifu-Vtuber#11]
When I start the run.py program and select 1 - Mic, and record the audio file, it keeps returning an Error Transcribing Audio error back and I can't seem to figure out what the issue is. I doubled check if the OpenAI auth key is correct and the input.wav file does have the audio inside, is there any way to fix it?

**Comment by RedBushido** [comment]
There is also another error that occurs in VSCode, which states that "ImportError: DLL load failed while importing _MeCab: The specified module could not be found." I already uninstalled and reinstalled MeCab and it still does not work.
![mecab](https://user-images.githubusercontent.com/89938207/227280003-5cf93e9b-658b-4904-81bc-f502c0dcb2cb.JPG)

**Comment by fskhri** [comment]
![image](https://user-images.githubusercontent.com/41115223/227444946-2e8a4c78-2d45-48bd-9ef0-4874ebf6ed03.png)

First，download Visual C++ redistributable

**Comment by ardha27** [comment]
You can try to follow this issue
https://github.com/ardha27/AI-Waifu-Vtuber/issues/5
Or if it cant be fixed you can just comment the katakana converter function in run.py since the program will still work
