### ISSUE TITLE
[Feature Request]: Get answers by writing, and totally free (no Openai API)

### ISSUE THREAD

**Issue by GiusTex** [ardha27/AI-Waifu-Vtuber#13]
Can this [webui](https://github.com/oobabooga/text-generation-webui) be integrated into your code? To not use OpenAi Api which is not free... (I know, I'm stingy). Anyway, the webui does not require a powerful computer, and supports several models. And based on this [video](https://www.youtube.com/watch?v=rGsnkkzV2_o&t=1080s&ab_channel=NerdyRodent) from minute 17:45 we see that the webui can also generate audio files (using the TTS extension).
**1.** So, can be added a 3° method, to write and pass the generated message to "speech_text" (if this is the right function) ?
**2.** Can the generated audio file be used to make the vtuber model's mouth move? I don't know if it's possible to pass the audio with/to the VB-Audio Virtual Cable, or if it's the right method. Maybe this way we don't need the voice synthesizer/text to speech

Edit:
1. I think that webui is too much complicated to use to write and get answers, to send then to ardha27's app, but maybe [this](https://github.com/nomic-ai/gpt4all) console is the right way. More details in the comments.
2. I managed to connect the virtual audio cable to the speakers and make the vtuber model talk when the webui produces responses (totally free, without using Openai Api), but I still think it would be nice to be able to switch between 3 modes with ardha27's app: use the mic or livechat when you stream, or just text if you don't stream and you don't want to make too much noise..

**Comment by ardha27** [comment]
1. that webui is using Seliro TTS for the voice synthesizer, and i already apply it on my repo just now, you can check it.
2. Yes, i use generated audio to make the vtuber model move, you can check on my demo/explain video on readme

**Comment by GiusTex** [comment]
Sorry I didn't explain myself well (long story); I wanted to write my message, not record it, this is why I suggested that webui. If the text option (the 3° method I mentioned at point one) can be added without the new webui, perfect

**Comment by ardha27** [comment]
Sorry i didn't get it well. So you want to use that webui for messaging and my code for doing TTS?

**Comment by ardha27** [comment]
oke, i understand. I also want to try to use another LLM for my project. But for now i never use other LLM beside OpenAI and i scared if i run LLM locally it will give burden on my pc since i will opening OBS, Vtubestudio for streaming. Because LLM will use many of VRAM https://github.com/oobabooga/text-generation-webui/wiki/System-requirements

**Comment by GiusTex** [comment]
Understood. And using it on Google collab? It requires a code a bit different but at least this way we have more computation power

**Comment by ardha27** [comment]
i still finding LLM code in colab that provide me API so i can call the API on my code

**Comment by GiusTex** [comment]
Sorry I don't understand the part about providing the api in your code on colab, can you reformulate?

**Comment by ardha27** [comment]
yes please, that will be nice

**Comment by GiusTex** [comment]
Oke
