### ISSUE TITLE
Failed to Transcribe Audio, no other errors

### ISSUE THREAD

**Issue by SacchanArea11** [ardha27/AI-Waifu-Vtuber#17]
I keep getting an immediate failed to transcribe error. I don't get any other information other than the terminal just saying that.
I'm running VoiceVox on Collab, my Open AI API key says it hasn't been used yet, running all this in PowerShell. 

Retracing my steps in a clean install- I Had some errors when installing the requirement.txt when it came to pyaudio.
[log.txt](https://github.com/ardha27/AI-Waifu-Vtuber/files/11154205/log.txt)
^Here's a log I made of the terminal since there's no error log present

**Comment by ardha27** [comment]
You can read FAQ about error transcribing audio on my readme

**Comment by SacchanArea11** [comment]
> > You can read FAQ about error transcribing audio on my readme
> 
> I got this here Traceback (most recent call last): File "C:\Users\Sakai\type4\Ageha\run.py", line 183, in record_audio() File "C:\Users\Sakai\type4\Ageha\run.py", line 64, in record_audio transcribe_audio("input.wav") File "C:\Users\Sakai\type4\Ageha\run.py", line 73, in transcribe_audio transcript = openai.Audio.transcribe("whisper-1", audio_file) File "C:\Users\Sakai\AppData\Local\Programs\Python\Python39\lib\site-packages\openai\api_resources\audio.py", line 57, in transcribe response, _, api_key = requestor.request("post", url, files=files, params=data) File "C:\Users\Sakai\AppData\Local\Programs\Python\Python39\lib\site-packages\openai\api_requestor.py", line 226, in request resp, got_stream = self._interpret_response(result, stream) File "C:\Users\Sakai\AppData\Local\Programs\Python\Python39\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response self._interpret_response_line( File "C:\Users\Sakai\AppData\Local\Programs\Python\Python39\lib\site-packages\openai\api_requestor.py", line 682, in _interpret_response_line raise self.handle_error_response( openai.error.AuthenticationError: Incorrect API key provided: Authoriz*************************************************************DG8W. You can find your API key at https://platform.openai.com/account/api-keys.
> 
> So I guess the API Key I had wasn't in the correct format or Open AI Rotated it
> 
> Gonna see what else I can do

Changed API Key, still don't work.

**Comment by ardha27** [comment]
How you place your api key, ss to me. Just censor/blur the api

**Comment by SacchanArea11** [comment]
> How you place your api key, ss to me. Just censor/blur the api

It's in the main folder as 'config.py'
Inside is as seen below
"Authorization: Bearer sk-************************************************"

Any other way of placing it gets a syntax error

Thanks for the quick responses by the way.

**Comment by ardha27** [comment]
Write it like this

api_key = 'yourapikey'

**Comment by SacchanArea11** [comment]
I figured it out, it was both the config.py fromat not being that plus "openai.api_key=" line having my API key there as well rather than referencing the config. However, now I must figure out how to get it to answer me in Japanese. The text keeps showing up as squares and it answers me in English.

Almost there!
