### ISSUE TITLE
sorry for distrub you creator but i will that other one since this other question

### ISSUE THREAD

**Issue by KiyoshiTheBoss** [ardha27/AI-Waifu-Vtuber#21]
i done the voice  vox in locally

C:\Users\60107>docker run --rm -it -p 50021:50021 voicevox/voicevox_engine:cpu-ubuntu20.04-latest
+ cat /opt/voicevox_engine/README.md
## 許諾内容

1. 商用・非商用問わず利用することができます
2. アプリケーションに組み込んで再配布することができます
3. 作成された音声を利用する際は、各音声ライブラリの規約に従ってください
4. 作成された音声の利用を他者に許諾する際は、当該他者に対し本許諾内容の 3 及び 4 の遵守を義務付けてください

### 四国めたん

四国めたんの音声ライブラリを用いて生成した音声は、
「VOICEVOX:四国めたん」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://zunko.jp/con_ongen_kiyaku.html

### ずんだもん

ずんだもんの音声ライブラリを用いて生成した音声は、
「VOICEVOX:ずんだもん」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://zunko.jp/con_ongen_kiyaku.html

### 春日部つむぎ

春日部つむぎの音声ライブラリを用いて生成した音声は、
「VOICEVOX:春日部つむぎ」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://tsumugi-official.studio.site/rule

### 波音リツ

波音リツの音声ライブラリを用いて生成した音声は、
「VOICEVOX:波音リツ」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
http://canon-voice.com/kiyaku.html

### 玄野武宏

玄野武宏の音声ライブラリを用いて生成した音声は、
「VOICEVOX:玄野武宏」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://virvoxproject.wixsite.com/official/voicevoxの利用規約

### 白上虎太郎

白上虎太郎の音声ライブラリを用いて生成した音声は、
「VOICEVOX:白上虎太郎」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://virvoxproject.wixsite.com/official/voicevoxの利用規約

### 青山龍星

個人が青山龍星の音声ライブラリを用いて生成した音声は、
「VOICEVOX:青山龍星」とクレジットを記載すれば、商用・非商用で利用可能です。
ただし企業が携わる形で利用する場合は、「ななはぴ(https://v.seventhh.com/contact/)」に対し事前確認を取る必要があります。

利用規約の詳細は以下をご確認ください。
https://virvoxproject.wixsite.com/official/voicevoxの利用規約

### 冥鳴ひまり

冥鳴ひまりの音声ライブラリを用いて生成した音声は、
「VOICEVOX:冥鳴ひまり」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://meimeihimari.wixsite.com/himari/terms-of-use

### 九州そら

九州そらの音声ライブラリを用いて生成した音声は、
「VOICEVOX:九州そら」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://zunko.jp/con_ongen_kiyaku.html

### もち子さん

もち子さんの音声ライブラリを用いて生成した音声は、
「VOICEVOX:もち子(cv 明日葉よもぎ)」とクレジットを記載すれば、
音声作品・音声素材・ゲーム作品を除いて商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://vtubermochio.wixsite.com/mochizora/利用規約

### 剣崎雌雄

剣崎雌雄の音声ライブラリを用いて生成した音声は、
「VOICEVOX:剣崎雌雄」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://frontier.creatia.cc/fanclubs/413/posts/4507

### WhiteCUL

WhiteCUL の音声ライブラリを用いて生成した音声は、
「VOICEVOX:WhiteCUL」とそれぞれクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://www.whitecul.com/guideline

### 後鬼

個人が後鬼の音声ライブラリを用いて生成した音声は、
「VOICEVOX:後鬼」とクレジットを記載すれば、商用・非商用で利用可能です。
ただし企業が携わる形で利用する場合は、「【鬼っ子ハンターついなちゃん】プロジェクト(https://ついなちゃん.com/mail/)」に対し事前確認を取る必要があります。

利用規約の詳細は以下をご確認ください。
https://ついなちゃん.com/voicevox_terms/

### No.7

個人が No.7 の音声ライブラリを用いて生成した音声は、
「VOICEVOX:No.7」とクレジットを記載すれば、非商用（同人利用や配信による収入は OK）で利用可能です。
その他商用利用の場合は、「No.7 製作委員会(https://voiceseven.com/)」に対し事前確認を取る必要があります。

利用規約の詳細は以下をご確認ください。
https://voiceseven.com/#j0200

### ちび式じい

ちび式じいの音声ライブラリを用いて生成した音声は、
「VOICEVOX:ちび式じい」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://docs.google.com/presentation/d/1AcD8zXkfzKFf2ertHwWRwJuQXjNnijMxhz7AJzEkaI4

### 櫻歌ミコ

櫻歌ミコの音声ライブラリを用いて生成した音声は、
「VOICEVOX:櫻歌ミコ」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://voicevox35miko.studio.site/rule

### 小夜/SAYO

小夜/SAYO の音声ライブラリを用いて生成した音声は、
「VOICEVOX:小夜/SAYO」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://316soramegu.wixsite.com/sayo-official/guideline

### ナースロボ＿タイプＴ

ナースロボ＿タイプＴの音声ライブラリを用いて生成した音声は、
「VOICEVOX:ナースロボ＿タイプＴ」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://www.krnr.top/rules

### †聖騎士 紅桜†

†聖騎士 紅桜†の音声ライブラリを用いて生成した音声は、
「VOICEVOX:†聖騎士 紅桜†」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://commons.nicovideo.jp/material/nc296132

### 雀松朱司

雀松朱司の音声ライブラリを用いて生成した音声は、
「VOICEVOX:雀松朱司」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://virvoxproject.wixsite.com/official/voicevoxの利用規約

### 麒ヶ島宗麟

麒ヶ島宗麟の音声ライブラリを用いて生成した音声は、
「VOICEVOX:麒ヶ島宗麟」とクレジットを記載すれば、商用・非商用で利用可能です。

利用規約の詳細は以下をご確認ください。
https://virvoxproject.wixsite.com/official/voicevoxの利用規約

## 禁止事項

- 逆コンパイル・リバースエンジニアリング及びこれらの方法の公開すること
- 製作者または第三者に不利益をもたらす行為
- 公序良俗に反する行為

## 免責事項

本ソフトウェアにより生じた損害・不利益について、製作者は一切の責任を負いません。

## その他

ご利用の際は VOICEVOX を利用したことがわかるクレジット表記が必要です。
+ exec gosu user /opt/python/bin/python3 ./run.py --voicelib_dir /opt/voicevox_core/ --runtime_dir /opt/onnxruntime/lib --host 0.0.0.0
Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )
INFO:     Started server process [1]
INFO:     Waiting for application startup.
reading /home/user/.local/share/voicevox-engine-dev/.tmp.dict_csv-dad18be8-87ce-4fe7-903b-9cc748494526 ... 57
emitting double-array: 100% |###########################################|

done!
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:50021 (Press CTRL+C to quit)

and i run like you did in vidoe 
PS C:\Users\60107\Downloads\AI-Waifu-Vtuber-master> python .\run.py
Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Question: Hello.
JP Answer: やあ。
Traceback (most recent call last):
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master\run.py", line 246, in <module>       
    record_audio()
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master\run.py", line 68, in record_audio    
    transcribe_audio("input.wav")
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master\run.py", line 87, in transcribe_audio
    openai_answer()
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master\run.py", line 123, in openai_answer  
    translate_text(message)
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master\run.py", line 201, in translate_text
    voicevox_tts(tts)
  File "C:\Users\60107\Downloads\AI-Waifu-Vtuber-master\utils\TTS.py", line 35, in voicevox_tts
    params_encoded = urllib.parse.urlencode({'text': katakana_text, 'speaker': 46})
                                                     ^^^^^^^^^^^^^
NameError: name 'katakana_text' is not defined

and still got this

**Comment by ardha27** [comment]
Change katakana_text to tts

**Comment by KiyoshiTheBoss** [comment]
it work
PS C:\Users\60107\Downloads\AI-Waifu-Vtuber-master> python .\run.py
Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Question: Hello, how are you?
JP Answer: 私は元気です。
Recording...
Stopped recording.
Question: Bagaimana keadaan kamu?
JP Answer: 良い。
