### ISSUE TITLE
AI doesnt answer at Twitch Live

### ISSUE THREAD

**Issue by grigorzero** [ardha27/AI-Waifu-Vtuber#23]
Hello, sorry for bothering you again.

I have question about twitch.

This is the code that i entered
server = 'irc.chat.twitch.tv'
port = 6667
nickname = 'testing'
token = 'oauth:qdgf4hsewydt5nw---- bla bla bla' # https://twitchapps.com/tmi/
user = 'grigorzero' # Your Twitch username
channel = 'GrigorZero' # The channel you want to retrieve messages from

I got "Error receiving chat" for trying to use the twitch live chat.
Do i have to change the channel into link when i live or i have to add #GrigorZero at channel?

I live right know to test the AI https://www.twitch.tv/grigorzero

**Comment by ardha27** [comment]
Yes, use #

**Comment by ardha27** [comment]
If #GrigorZero dont work, try #grigorzero

**Comment by grigorzero** [comment]
Sad, it is still "Error receiving chat"

**Comment by ardha27** [comment]
i can do it just now 
![image](https://user-images.githubusercontent.com/48845217/230622791-3bb6d268-ce71-41fd-b579-a64f0704d10a.png)

**Comment by ardha27** [comment]
how about you try to delete the try-except on this section of code. So it will give you more iformation about the error 
![image](https://user-images.githubusercontent.com/48845217/230623224-8cadb4af-c0c7-4b1e-b774-cf6db894c18a.png)

**Comment by grigorzero** [comment]
Hmm, i already try to delete the try-except. It still didn't work, The AI can answer my voice and youtube chat too, but it didnt work on twitch. 
 
It is still stuck at:

To use this mode, make sure to change utils/twitch_config.py to your own config


Im gonna wait if there is new update, thank you anyway

**Comment by unsusteinable12** [comment]
i added the following as a fourth option 

def twitch_chats():
    global chat

    SERVER = "irc.chat.twitch.tv"
    PORT = 6667
    NICKNAME = "putyouruserhere"
    TOKEN = 'putyourtokenhere'
    CHANNEL = "#putyourchannelhere"
    irc = socket.socket()
    irc.connect((SERVER, PORT))

    irc.send(f"PASS {TOKEN}\n".encode("utf-8"))
    irc.send(f"NICK {NICKNAME}\n".encode("utf-8"))
    irc.send(f"JOIN {CHANNEL}\n".encode("utf-8"))

    while True:
        message = irc.recv(2048).decode("utf-8")
        if message.startswith("PING"):
            irc.send("PONG\n".encode("utf-8"))
        elif len(message) > 0:
            username = message.split("!")[0][1:]
            message_content = ":".join(message.split(":")[2:])
            print(f"{username}: {message_content}")

            chat = username + ' said ' + message
            print(chat)




and this at the end of the code 
        elif mode == "4":
            # Threading is used to capture livechat and answer the chat at the same time
            print("Be sure to have your channelkey and username on the code")
            t = threading.Thread(target=preparation)
            t.start()
            twitch_chats()

![aqui](https://user-images.githubusercontent.com/130176388/230708768-44cb38a3-b794-4dc9-89a7-3842b80cbef8.png)


Seems to have worked for me ! its reading the messages and responding but had to set it up like that otherwise it just kept saying error reading chat

**Comment by grigorzero** [comment]
OH MY GOD, IT WORK!!! 

> i added the following as a fourth option
> 
> def twitch_chats(): global chat
> 
> ```
> SERVER = "irc.chat.twitch.tv"
> PORT = 6667
> NICKNAME = "putyouruserhere"
> TOKEN = 'putyourtokenhere'
> CHANNEL = "#putyourchannelhere"
> irc = socket.socket()
> irc.connect((SERVER, PORT))
> 
> irc.send(f"PASS {TOKEN}\n".encode("utf-8"))
> irc.send(f"NICK {NICKNAME}\n".encode("utf-8"))
> irc.send(f"JOIN {CHANNEL}\n".encode("utf-8"))
> 
> while True:
>     message = irc.recv(2048).decode("utf-8")
>     if message.startswith("PING"):
>         irc.send("PONG\n".encode("utf-8"))
>     elif len(message) > 0:
>         username = message.split("!")[0][1:]
>         message_content = ":".join(message.split(":")[2:])
>         print(f"{username}: {message_content}")
> 
>         chat = username + ' said ' + message
>         print(chat)
> ```
> 
> and this at the end of the code elif mode == "4": # Threading is used to capture livechat and answer the chat at the same time print("Be sure to have your channelkey and username on the code") t = threading.Thread(target=preparation) t.start() twitch_chats()
> 
> ![aqui](https://user-images.githubusercontent.com/130176388/230708768-44cb38a3-b794-4dc9-89a7-3842b80cbef8.png)
> 
> Seems to have worked for me ! its reading the messages and responding but had to set it up like that otherwise it just kept saying error reading chat

OH MY GOD IT WORK!!!

There is no option 4, i have to write 4 myself and it did work!! 

if __name__ == "__main__":
    try:
        # You can change the mode to 1 if you want to record audio from your microphone
        # or change the mode to 2 if you want to capture livechat from youtube
        mode = input("Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): ")

        if mode == "1":
            print("Press and Hold Right Shift to record audio")
            while True:
                if keyboard.is_pressed('RIGHT_SHIFT'):
                    record_audio()
            
        elif mode == "2":
            live_id = input("Livestream ID: ")
            # Threading is used to capture livechat and answer the chat at the same time
            t = threading.Thread(target=preparation)
            t.start()
            yt_livechat(live_id)

        elif mode == "3":
            # Threading is used to capture livechat and answer the chat at the same time
            print("To use this mode, make sure to change utils/twitch_config.py to your own config")
            t = threading.Thread(target=preparation)
            t.start()
            twitch_livechat()
        elif mode == "4":
            # Threading is used to capture livechat and answer the chat at the same time
            print("Be sure to have your channelkey and username on the code")
            t = threading.Thread(target=preparation)
            t.start()
            twitch_chats()

Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 4


Thank you so much Unsusteinable12 and Ardha!!

**Comment by ardha27** [comment]
hmm, how can it works? i didn't see much different with my code

**Comment by unsusteinable12** [comment]
Hmm the only major difference that i saw was that i put all the twitch config inside of the same run code,  thats the only thing that i did different

**Comment by grigorzero** [comment]
I drop the code that given by unsusteinable at run.py and not the twitch_config. I dunno why it work, it just did

**Comment by ardha27** [comment]
> Hmm the only major difference that i saw was that i put all the twitch config inside of the same run code, thats the only thing that i did different



> I drop the code that given by unsusteinable at run.py and not the twitch_config. I dunno why it work, it just did

that is coding 😭

**Comment by grigorzero** [comment]
lol, thank you @ardha27 @unsusteinable12 , you guys are epic

**Comment by Sylensar** [comment]
This is my final step. I cant seem to format the code correct. Do I just copy and paste it into my run.py file? If so where exactly do I put it? on which line?

**Comment by wetzernutz** [comment]
for anyone who doesnt understand:
 
 ```python
 def twitch_chats():
     global chat
     SERVER = "irc.chat.twitch.tv"
     PORT = 6667
     NICKNAME = "putyouruserhere"
     TOKEN = 'putyourtokenhere'
     CHANNEL = "#putyourchannelhere"
     irc = socket.socket()
     irc.connect((SERVER, PORT))
 
     irc.send(f"PASS {TOKEN}\n".encode("utf-8"))
     irc.send(f"NICK {NICKNAME}\n".encode("utf-8"))
     irc.send(f"JOIN {CHANNEL}\n".encode("utf-8"))
 
     while True:
         message = irc.recv(2048).decode("utf-8")
         if message.startswith("PING"):
             irc.send("PONG\n".encode("utf-8"))
         elif len(message) > 0:
             username = message.split("!")[0][1:]
             message_content = ":".join(message.split(":")[2:])
             print(f"{username}: {message_content}")
 
             chat = username + ' said ' + message
             print(chat)
 ```
 
 ```python
         elif mode == "4":
             # Threading is used to capture livechat and answer the chat at the same time
             print("Be sure to have your channelkey and username on the code")
             t = threading.Thread(target=preparation)
             t.start()
             twitch_chats()
```

they added a new function twitch_chats and added a new elif condition at the bottom if else statement.
 just insert the upper code into these places. be careful of the spacing it should look exactly like this.

<img alt="Screenshot 2023-05-25 at 10 20 30 PM" width="1512" src="https://user-images.githubusercontent.com/126750514/240945811-3d8ec569-45c2-4ab6-8a7d-c0f15ed65e89.png"> <img alt="Screenshot 2023-05-25 at 10 22 31 PM" width="1512" src="https://user-images.githubusercontent.com/126750514/240946093-12ccb29f-f2da-4a89-945c-d67cbc6b3e50.png">

**Comment by Sylensar** [comment]
This saved me.

**Comment by wetzernutz** [comment]
@Sylensar can u accept my discord invitation?

**Comment by Sylensar** [comment]
doing so now @wetzernutz
