### ISSUE TITLE
Pip & Run

### ISSUE THREAD

**Issue by ShiCav** [ardha27/AI-Waifu-Vtuber#27]
When i try to "pip install -r requirements.txt"it installs half of them then gives me errors for the rest such as PYAudio, and whenever i do "python run.py" it says line 8 in module import keyboard, No module named keyboard.

![image_2023-04-09_080430276](https://user-images.githubusercontent.com/93087708/230753677-752ee388-e737-4fac-8364-b875eab68982.png)
![image_2023-04-09_080449431](https://user-images.githubusercontent.com/93087708/230753686-3aec85dc-1765-4a84-b859-790a7a8f0b30.png)

**Comment by ardha27** [comment]
You can try to install it separately

pip install pyaudio
pip install keyboard

**Comment by ShiCav** [comment]
when i tried pyaudio it says already met requirment but the installing keyboard worked, now i get another error message when running "python run.py"
![image_2023-04-09_085309976](https://user-images.githubusercontent.com/93087708/230755024-feaf2320-e117-4522-819d-3643c65ddde7.png)
and i pip installed emoji then it gave me another error and i installed it again then another error, so i assume i just keep installing what it asks of me one by one?

**Comment by ardha27** [comment]
Yes, it can be alternative

**Comment by ShiCav** [comment]
now i'm getting error transcribing audio but i think someone already made a ticket for it

**Comment by ardha27** [comment]
You can see the FAQ on readme

**Comment by ShiCav** [comment]
![Uploading image_2023-04-09_091010463.png…]()

**Comment by ardha27** [comment]
Update your openai library

**Comment by ShiCav** [comment]
i'm sorry for using up your time but i got another error haha
![image_2023-04-09_091814614](https://user-images.githubusercontent.com/93087708/230755744-b4c1744b-7b28-4deb-8aa3-9ffedb20764f.png)

**Comment by ShiCav** [comment]
i dont deepl pro in my country so i did the same you did in the video

**Comment by ardha27** [comment]
You need to use the same version of googletrans like i use on requirements.txt

**Comment by ShiCav** [comment]
Thank you it fixed it!
