### ISSUE TITLE
Upgrading 

### ISSUE THREAD

**Issue by shioridotdev** [ardha27/AI-Waifu-Vtuber#3]
hello it is nice for tagging me,
i going update work using gpu base container, and new solution to out balance workload on host. hope to make solution more nice, thanks again

**Comment by ardha27** [comment]
i'm waiting for your update

**Comment by shioridotdev** [comment]
it is last update 0.9, will release at 1.0 soon
hope you will like change

**Comment by ardha27** [comment]
okay, i will try it later
