### ISSUE TITLE
how to run this in macbook?

### ISSUE THREAD

**Issue by Darelllf** [ardha27/AI-Waifu-Vtuber#30]
actually the winsound only work for windows and macbook can run it, do you have any solution?

**Comment by ardha27** [comment]
![image](https://user-images.githubusercontent.com/48845217/230876570-9ef9ed53-36f9-4928-8eea-932b10dcdd17.png)
import pygame

pygame.mixer.init()
pygame.mixer.music.load("sound_file.wav")
pygame.mixer.music.play()
