### ISSUE TITLE
Youtube livestream works?

### ISSUE THREAD

**Issue by Rempacious** [ardha27/AI-Waifu-Vtuber#4]
![image](https://user-images.githubusercontent.com/73411987/225598764-07a94189-2bd8-4a03-8664-0db0e3c79c2c.png)
Do I need to setup something else to work? It somehow doesn't get any chats from a livestream

**Comment by ardha27** [comment]
Is that your own stream or other people stream? If it your own stream, make sure to start your stream from obs before you run the code. To try the program, you can also use other people stream id first

**Comment by Rempacious** [comment]
Tried with other streams and it worked. It's probably because I run the code first before the stream. Thanks.

**Comment by ardha27** [comment]
Ahh yeah you can change it on the code
