### ISSUE TITLE
Problems during code run

### ISSUE THREAD

**Issue by Miehua** [ardha27/AI-Waifu-Vtuber#5]
I have used English translation software, so please excuse any inaccuracies. I followed the instructions and entered the openai key, downloaded the VOICEVOX file and ran it on Docker, also updated and installed the openai and other modules, then ran python run.py in the terminal and it came up with Recording..., Stopped recording, Question: Hello, Error transcribing audio. I'm getting Recording..., Stopped recording, Question: Hello, Error transcribing audio. I did record the voice, but only the question was displayed, not the answer, and the result was Error transcribing audio.

**Comment by ardha27** [comment]
i do a little change on my run.py code just now, can you run it again? it must show you what is the error exactly

**Comment by Miehua** [comment]
After installing googletrans 4.0.0
This time there is a better progress than the last time

This time the question is
PS E:\AISUPER\AI-Waifu-Vtuber-master> python run.py
Mode (1-Microphone, 2-Youtube Live). 1
Hold right click and record audio
Recording...
Stopped recording.
Question. Hello, how are you?
ID answer. saya model bahasa AI, saya tidak memiliki emosi.
JP Answer: 私はAI言语モデルです，私は感情を持有っていません。
Backtrack (last call).
  File "E:\AISUPER\AI-Waifu-Vtuber-master\run.py", line 218, in <module>.
    record_audio()
  File "E:\AISUPER\AI-Waifu-Vtuber-master\run.py", line 67, in record_audio
    transcribe_audio("input.wav")
  File "E:\AISUPER\AI-Waifu-Vtuber-master\run.py", line 86, in transcribe_audio
    openai_answer()
  File "E:\AISUPER\AI-Waifu-Vtuber-master\run.py", line 110, in openai_answer
    translate_text(message)
  File "E:\AISUPER\AI-Waifu-Vtuber-master\run.py", line 141, in translate_text
    speech_text(result_jp, result_id)
  File "E:\AISUPER\AI-Waifu-Vtuber-master\run.py", line 148, in speech_text
    katakana_text = katakana_converter(result_jp)
  File "E:\AISUPER\AI-Waifu-Vtuber-master\katakana.py", line 15, in katakana_converter
    wakati = MeCab.Tagger('-Owakati')
  File "F:\Python310\lib\site-packages\MeCab.py", line 355, in __init__
    _MeCab.Tagger_swiginit(self, _MeCab.new_Tagger(*args))
Runtime errors

Now I know the reason for not showing Qusetion is that openai's module is not updated


Translated with www.DeepL.com/Translator (free version)

**Comment by ardha27** [comment]
It's look like you are not installed unidic lib properly. According to this https://pypi.org/project/unidic/
After you installing unidic, you need to run this command

python -m unidic download

**Comment by Miehua** [comment]
Hi author, I'm still getting errors even after installing unidic and python -m unidic download on the first try (same error as last time).
So I wondered if it was a MeCab problem, so I downloaded MeCab.exe from GitHub and installed it (although python already had it).
At this point I ran python run.py in the terminal and it worked, it was slow but I was happy and I thank you for your patience.
This is the first time I have installed and solved a problem on GitHub, and I feel the power of working together from all over the world, thank you!
My summary of some of the issues
The old version of Openai doesn't seem to include Whisper, so I can't see the problem
My python 3.10 installation of googletrans defaults to version 3.0.0.

**Comment by ardha27** [comment]
glad to hear that your code run well, if it was slow you can run the voicevox engine on cloud or google colab instead of running it locally. you can try this to run it on colab
https://github.com/SociallyIneptWeeb/LanguageLeapAI/blob/main/src/run_voicevox_colab.ipynb

**Comment by Miehua** [comment]
Hello Author
I saw your video on Youtube https://youtu.be/qpNG9qrcmrQ
Because of some policy reasons in our country we can't watch the videos of foreign software directly, but need VPN to watch them.
I would like to show my friends the effect of the AI vtuber answer clip in your video in the platform of the domestic software (similar to instagram and WeChat), I don't know if it is possible, I need your permission.
I will not use it commercially, and I will mark the source and origin of the video, as well as your name
Another aspect is that when I open OBS and Vtube studio software, my computer is too laggy and it is hard to record smooth videos.
Thanks again for the author's willingness to share open source and write the code hard.

**Comment by ardha27** [comment]
yes you can share my video

**Comment by N3CH0** [comment]
I have the same issue, but I cant figure it out how to fix it or what mecab I should download from GitHub?

**Comment by Miehua** [comment]
I download it from website,this is the MeCab Google link,you can choose your needed inside.
https://drive.google.com/drive/folders/0B4y35FiV1wh7fjQ5SkJETEJEYzlqcUY4WUlpZmR4dDlJMWI5ZUlXN2xZN2s2b0pqT3hMbTQ?resourcekey=0-VaHzcd_V8qgKt66qJDufGw

**Comment by N3CH0** [comment]
Looks like there's a bunch of version of MeCab, I tried the .exe and the python one but none are successful, so what MeCab version should I download?

**Comment by Miehua** [comment]
The branches are just different versions, just download the latest installation and install it again.
By the way, can you be more specific about your problem?

**Comment by N3CH0** [comment]
Here is my error log :
Traceback (most recent call last):
  File "C:\oof\AI\AI-Waifu-Vtuber-master\run.py", line 211, in <module>   
    record_audio()
  File "C:\oof\AI\AI-Waifu-Vtuber-master\run.py", line 67, in record_audio
    transcribe_audio("input.wav")
  File "C:\oof\AI\AI-Waifu-Vtuber-master\run.py", line 85, in transcribe_audio
    openai_answer()
  File "C:\oof\AI\AI-Waifu-Vtuber-master\run.py", line 108, in openai_answer
    translate_text(message)
  File "C:\oof\AI\AI-Waifu-Vtuber-master\run.py", line 137, in translate_text
    speech_text(result_jp, result_id)
  File "C:\oof\AI\AI-Waifu-Vtuber-master\run.py", line 143, in speech_text
    katakana_text = katakana_converter(result_jp)
  File "C:\oof\AI\AI-Waifu-Vtuber-master\katakana.py", line 15, in katakana_converter
    wakati = MeCab.Tagger('-Owakati')
  File "C:\Users\asus\AppData\Local\Programs\Python\Python310\lib\site-packages\MeCab.py", line 355, in __init__
    _MeCab.Tagger_swiginit(self, _MeCab.new_Tagger(*args))
RuntimeError

Seems like the MeCab is the problem

**Comment by N3CH0** [comment]
I manage to fix it!
I download MeCab for python3 and it works, so for the trouble that I made :(

**Comment by Miehua** [comment]
I'm sorry I just saw your message, and I'm glad you were able to run the software successfully. A little curious as to what country you are from? ᐇ

**Comment by novalriza** [comment]
bang mohon penjelasan nya saya tidak bisa install modul pyopenjtalk

Defaulting to user installation because normal site-packages is not writeable
Collecting pyopenjtalk
  Using cached pyopenjtalk-0.3.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [43 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      -- Building for: NMake Makefiles
      CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
        Compatibility with CMake < 2.8.12 will be removed from a future version of
        CMake.
     
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
     
     
      CMake Error at CMakeLists.txt:17 (project):
        Running
     
         'nmake' '-?'
     
        failed with:
     
         The system cannot find the file specified
     
     
      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\Kawaii\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Kawaii\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Kawaii\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Kawaii\AppData\Local\Temp\pip-build-env-hoo88ctw\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\Kawaii\AppData\Local\Temp\pip-build-env-hoo88ctw\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires        
          self.run_setup()
        File "C:\Users\Kawaii\AppData\Local\Temp\pip-build-env-hoo88ctw\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Kawaii\AppData\Local\Temp\pip-build-env-hoo88ctw\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 154, in <module>
        File "C:\Program Files\Python310\lib\subprocess.py", line 457, in check_returncode
      subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\Kawaii\Downloads\Ai\voicevox_engine-master> python .\run.py
Traceback (most recent call last):
  File "C:\Users\Kawaii\Downloads\Ai\voicevox_engine-master\run.py", line 29, in <module>
    from voicevox_engine.cancellable_engine import CancellableEngine
  File "C:\Users\Kawaii\Downloads\Ai\voicevox_engine-master\voicevox_engine\cancellable_engine.py", line 16, in <module>
    from .synthesis_engine import make_synthesis_engines
  File "C:\Users\Kawaii\Downloads\Ai\voicevox_engine-master\voicevox_engine\synthesis_engine\__init__.py", line 2, in <module>
    from .make_synthesis_engines import make_synthesis_engines
  File "C:\Users\Kawaii\Downloads\Ai\voicevox_engine-master\voicevox_engine\synthesis_engine\make_synthesis_engines.py", line 8, in <module>
    from .synthesis_engine import SynthesisEngine, SynthesisEngineBase
  File "C:\Users\Kawaii\Downloads\Ai\voicevox_engine-master\voicevox_engine\synthesis_engine\synthesis_engine.py", line 11, in <module>
    from .synthesis_engine_base import SynthesisEngineBase
  File "C:\Users\Kawaii\Downloads\Ai\voicevox_engine-master\voicevox_engine\synthesis_engine\synthesis_engine_base.py", line 7, in <module>
    from .. import full_context_label
  File "C:\Users\Kawaii\Downloads\Ai\voicevox_engine-master\voicevox_engine\full_context_label.py", line 6, in <module>
    import pyopenjtalk
ModuleNotFoundError: No module named 'pyopenjtalk'

**Comment by Miehua** [comment]
you can try it first in python
pip install pyopenjtalk
after done it,you can show me other problem
By the way,my English is poor,i will try my best to fix your problem.

**Comment by novalriza** [comment]
SETELAH SAYA pip install pyopenjtalk TETAP SAJA HASILNYA SEPERTI ITU

**Comment by Miehua** [comment]
It looks like there are a few errors happening here. The first error is related to the installation of the pyopenjtalk package where it failed to retrieve the requirements to build the wheel. The second error seems to be related to the engine you are using, where it cannot find the pyopen jtalk module.

To resolve the first error, you may want to try running pip install again with the --no-cache-dir option:

pip install pyopenjtalk --no-cache-dir

For the second error, it looks like the engine is not able to find the pyopenjtalk module. You may want to check if you have installed it correctly and if it is in your Python environment's PATH.

**Comment by KiyoshiTheBoss** [comment]
i got this problem can somoene help



PS C:\Users\60107\Desktop\AI-Waifu-Vtuber-master> & "C:/Program Files/Python311/python.exe" c:/Users/60107/Desktop/AI-Waifu-Vtuber-master/run.py
Traceback (most recent call last):
  File "c:\Users\60107\Desktop\AI-Waifu-Vtuber-master\run.py", line 16, in <module>
    from katakana import *
  File "c:\Users\60107\Desktop\AI-Waifu-Vtuber-master\katakana.py", line 1, in <module>
    import MeCab
  File "C:\Users\60107\AppData\Roaming\Python\Python311\site-packages\MeCab\__init__.py", line 10, in <module>
    from . import _MeCab
ImportError: DLL load failed while importing _MeCab: The specified module could not be found.

**Comment by N3CH0** [comment]
> I'm sorry I just saw your message, and I'm glad you were able to run the software successfully. A little curious as to what country you are from? ᐇ

And I'm sry too, I was a little busy, I'm from Indonesia but I can use English well...... 
Well it's because English is common for me. Where're you came from? Lmao

**Comment by N3CH0** [comment]
> i still got the same problem even with C++++

Can you give the error log?

**Comment by KiyoshiTheBoss** [comment]
> > i still got the same problem even with C++++
> 
> Can you give the error log?
> 
> That will give us a context of what happen, just copy paste it

the same error at terminal

**Comment by KiyoshiTheBoss** [comment]
> > i still got the same problem even with C++++
> 
> Can you give the error log?
> 
> That will give us a context of what happen, just copy paste it

PS C:\Users\60107\Desktop\AI-Waifu-Vtuber-master> python run.py
Traceback (most recent call last):
  File "C:\Users\60107\Desktop\AI-Waifu-Vtuber-master\run.py", line 16, in <module>    
    from katakana import *
  File "C:\Users\60107\Desktop\AI-Waifu-Vtuber-master\katakana.py", line 1, in <module>
    import MeCab
  File "C:\Users\60107\AppData\Roaming\Python\Python311\site-packages\MeCab\__init__.py", line 10, in <module>
    from . import _MeCab
ImportError: DLL load failed while importing _MeCab: The specified module could not be found.

and i also got this

**Comment by KiyoshiTheBoss** [comment]
The environment variable 'Path' seems to have some paths containing the '"' character. The existence of such a character is known to have caused the Python extension to not load. If the extension fails to load please modify your paths to remove this '"' character.

**Comment by novalriza** [comment]
TOLONG BANTU SAYA ,SAYA MENJALANKAN VOICEVOX ANGINE DAN TERJADI SEPERTI INI Warning: cpu_num_threads is set to 0. ( The library leaves the decision to the synthesis runtime )
Traceback (most recent call last):
  File "C:\Users\Kawaii\Downloads\hhh\voicevox_engine-master\run.py", line 1169, in <module>
    synthesis_engines = make_synthesis_engines(
  File "C:\Users\Kawaii\Downloads\hhh\voicevox_engine-master\voicevox_engine\synthesis_engine\make_synthesis_engines.py", line 96, in make_synthesis_engines
    load_core_library(core_dir)
  File "C:\Users\Kawaii\Downloads\hhh\voicevox_engine-master\voicevox_engine\synthesis_engine\make_synthesis_engines.py", line 81, in load_core_library
    core = CoreWrapper(use_gpu, core_dir, cpu_num_threads, load_all_models)
  File "C:\Users\Kawaii\Downloads\hhh\voicevox_engine-master\voicevox_engine\synthesis_engine\core_wrapper.py", line 360, in __init__
    self.core = load_core(core_dir, use_gpu)
  File "C:\Users\Kawaii\Downloads\hhh\voicevox_engine-master\voicevox_engine\synthesis_engine\core_wrapper.py", line 320, in load_core
    raise RuntimeError("コアが見つかりません")
RuntimeError: コアが見つかりません

**Comment by atashikao** [comment]
saya di buat sakit kepala dengan error ini kwowkow tolong 😵‍💫

Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
_**Question: . . . . .
Error detect
Error translate
Error translate
Error translating text**_

**Comment by ardha27** [comment]
> saya di buat sakit kepala dengan error ini kwowkow tolong 😵‍💫
> 
> Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
> Press and Hold Right Shift to record audio
> Recording...
> Stopped recording.
> _**Question: . . . . .
> Error detect
> Error translate
> Error translate
> Error translating text**_
> 

Pastikan versi google translate mu sama seperti versi di requirements.txt

**Comment by atashikao** [comment]
> > saya di buat sakit kepala dengan error ini kwowkow tolong 😵‍💫
> > Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
> > Press and Hold Right Shift to record audio
> > Recording...
> > Stopped recording.
> > _**Question: . . . . .
> > Error detect
> > Error translate
> > Error translate
> > Error translating text**_
> 
> Pastikan versi google translate mu sama seperti versi di requirements.txt

berhasiil juragan... 
bot sudah bisa menjawab pertanyaan, tapi agak delay..
dan gimana caranya biar ngomong jp? ane gagal paham di bagian [VoiceVox Docker] 
punya ane ngomong indo pake logat inggris kwowkoww  tolong maafin...

**Comment by ardha27** [comment]
Voicevoxnya harus dijalankan dulu, boleh di docker atau di colab

**Comment by atashikao** [comment]
> Voicevoxnya harus dijalankan dulu, boleh di docker atau di colab

yg atas fix, mentep,,,

ada lagi nih, kwowkwo misal saya bertanya, di terminal nongol jawaban, tapi si ai malah baca yg lain, tidak sesuai dengan yg di terminal.. dan itu trus jawabanya.. ( watashi wa program apa gitu kan... ) salahnya di bagian mane ?

**Comment by ardha27** [comment]
Coba kirimin isi conversation.json mu

**Comment by atashikao** [comment]
> Coba kirimin isi conversation.json mu

`{
    "history": [
        {
            "role": "user",
            "content": "malik said Sekarang hari apa?"
        },
        {
            "role": "assistant",
            "content": "Jumat."
        },
        {
            "role": "user",
            "content": "malik said Bagaimana ini bisa terjadi? Kenapa Anda berbicara itu terus?"
        },
        {
            "role": "assistant",
            "content": "Karena saya diciptakan untuk berbicara."
        },
        {
            "role": "user",
            "content": "malik said Tolong sebutkan keajaiban dunia minimal 3"
        },
        {
            "role": "assistant",
            "content": "Temple Taj Mahal, Colosseum, Great Wall."
        },
        {
            "role": "user",
            "content": "malik said tunggu sebentar saya akan bertanya ke master anda, master ardha"
        }
    ]
}`

**Comment by atashikao** [comment]
{
    "history": [
        {
            "role": "user",
            "content": "malik said Sekarang hari apa?"
        },
        {
            "role": "assistant",
            "content": "Jumat."
        },
        {
            "role": "user",
            "content": "malik said Bagaimana ini bisa terjadi? Kenapa Anda berbicara itu terus?"
        },
        {
            "role": "assistant",
            "content": "Karena saya diciptakan untuk berbicara."
        },
        {
            "role": "user",
            "content": "malik said Tolong sebutkan keajaiban dunia minimal 3"
        },
        {
            "role": "assistant",
            "content": "Temple Taj Mahal, Colosseum, Great Wall."
        },
        {
            "role": "user",
            "content": "malik said tunggu sebentar saya akan bertanya ke master anda, master ardha"
        }
    ]
}

**Comment by atashikao** [comment]
kalau di terminal tampilan seperti ini


Mode (1-Mic, 2-Youtube Live, 3-Twitch Live): 1
Press and Hold Right Shift to record audio
Recording...
Stopped recording.
Question: Sekarang hari apa?
JP Answer: 金曜日です。
EN Answer: Friday.
Recording...
Stopped recording.
Question: Bagaimana ini bisa terjadi? Kenapa Anda berbicara itu terus?
JP Answer: なぜなら、私は話すために作られたからです。
EN Answer: Because I was created to speak.
Recording...
Stopped recording.
Question: Tolong sebutkan keajaiban dunia minimal 3
JP Answer: タージマハル寺院、コロッセオ、万里の長城。
EN Answer: Temple Taj Mahal, Colosseum, Great Wall.
Recording...
Stopped recording.
Question: tunggu sebentar saya akan bertanya ke master anda, master ardi
JP Answer: そうですか。
EN Answer: Good.

**Comment by ardha27** [comment]
Dari jawabannya ga ada masalah

**Comment by atashikao** [comment]
> Dari jawabannya ga ada masalah

nah ittu dia.. salah input 
coba diralat

![image](https://user-images.githubusercontent.com/30452212/230782161-2353755c-58cc-4986-b242-bd0e0a612b52.png)

**Comment by ardha27** [comment]
Sorry aku kurang paham, jadi permasalahannya apa

**Comment by atashikao** [comment]
> Sorry aku kurang paham, jadi permasalahannya apa

siap gan... ane obrak abrik lagi dah ty ty untuk bantuan sebelumnya

**Comment by ardha27** [comment]
Maksudnya aku kurang paham permasalahan mu, bukan kurang paham solusinya 😭

**Comment by atashikao** [comment]
> Maksudnya aku kurang paham permasalahan mu, bukan kurang paham solusinya 😭

akwowkwokw maafin hamba ....  
yg jelas dia sih udah bner ini, cuman kurang polesan dikit.. tapi ntah dimana itu... ane curiga bau2nya di katakana_converter dah

**Comment by atashikao** [comment]
> Maksudnya aku kurang paham permasalahan mu, bukan kurang paham solusinya 😭

kaya gini https://youtu.be/YKT017q_9zc

**Comment by ardha27** [comment]
Kurang polesan dikit tu gmn

**Comment by ardha27** [comment]
Itu mah output.wav nya ga berubah, voicevox mu gagal ngegenerate/synthesize audinya kemungkinan. Jadi yg diputer output.wav yg lama terus

**Comment by atashikao** [comment]
> Itu mah output.wav nya ga berubah, voicevox mu gagal ngegenerate/synthesize audinya kemungkinan. Jadi yg diputer output.wav yg lama terus

jadi ane harus ngobok2 di bagian voicevox supa bia ter syn audionya... lanjutkan

**Comment by ardha27** [comment]
Coba main" di utils/TTS.py panggil fungsi voicevox disana

**Comment by atashikao** [comment]
> voicevox mu gagal ngegenerate/synthesize audinya kemungkinan

siap gan.... tar kalo nyerah balik lagi kemari kwowkoww
