### ISSUE TITLE
exceeded your current quota

### ISSUE THREAD

**Issue by WillyTC05** [ardha27/AI-Waifu-Vtuber#53]
Hi, When running the program and selecting mode 1 (Microphone), I encounter this error: 'Error transcribing audio: You exceeded your current quota, please check your plan and billing details.' 
How do I fix it?

**Comment by ardha27** [comment]
i think your free api is on limit, you need to buy the paid plan

**Comment by Alym3244** [comment]
by api is meant the api from openai?
