### ISSUE TITLE
AssertionError: `speaker` should be in fr_0, fr_1, fr_2, fr_3, fr_4, fr_5, random

### ISSUE THREAD

**Issue by OkoTale** [ardha27/AI-Waifu-Vtuber#54]
```
Traceback (most recent call last):
  File "C:\Users\lecri\Desktop\AI-Waifu-Vtuber-master\run.py", line 261, in <module>
    record_audio()
  File "C:\Users\lecri\Desktop\AI-Waifu-Vtuber-master\run.py", line 70, in record_audio
    transcribe_audio("input.wav")
  File "C:\Users\lecri\Desktop\AI-Waifu-Vtuber-master\run.py", line 91, in transcribe_audio
    openai_answer()
  File "C:\Users\lecri\Desktop\AI-Waifu-Vtuber-master\run.py", line 126, in openai_answer
    translate_text(message)
  File "C:\Users\lecri\Desktop\AI-Waifu-Vtuber-master\run.py", line 217, in translate_text
    silero_tts(tts_en, "en", "v3_en", "en_en")
  File "C:\Users\lecri\Desktop\AI-Waifu-Vtuber-master\utils\TTS.py", line 23, in silero_tts
    audio_paths = model.save_wav(text=tts,
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<torch_package_0>.multi_acc_v3_package.py", line 366, in save_wav
  File "<torch_package_0>.multi_acc_v3_package.py", line 303, in apply_tts
AssertionError: `speaker` should be in fr_0, fr_1, fr_2, fr_3, fr_4, fr_5, random
```

**Comment by ardha27** [comment]
No valid input on silero tts function

**Comment by OkoTale** [comment]
here's my tts :

`import os
import torch
import requests
import urllib.parse
from utils.katakana import *

# https://github.com/snakers4/silero-models#text-to-speech
def silero_tts(tts, language, model, speaker):
    device = torch.device('cpu')
    torch.set_num_threads(4)
    local_file = 'model.pt'

    if not os.path.isfile(local_file):
        torch.hub.download_url_to_file(f'https://models.silero.ai/models/tts/{language}/{model}.pt',
                                    local_file)  

    model = torch.package.PackageImporter(local_file).load_pickle("tts_models", "model")
    model.to(device)

    example_text = "i'm fine thank you and you?"
    sample_rate = 48000

    audio_paths = model.save_wav(text=tts,
                                speaker=speaker,
                                sample_rate=sample_rate)
    
def voicevox_tts(tts):
    # You need to run VoicevoxEngine.exe first before running this script
    
    voicevox_url = 'http://localhost:50021'
    # Convert the text to katakana. Example: ORANGE -> オレンジ, so the voice will sound more natural
    katakana_text = katakana_converter(tts)
    # You can change the voice to your liking. You can find the list of voices on speaker.json
    # or check the website https://voicevox.hiroshiba.jp
    params_encoded = urllib.parse.urlencode({'text': katakana_text, 'speaker': 46})
    request = requests.post(f'{voicevox_url}/audio_query?{params_encoded}')
    params_encoded = urllib.parse.urlencode({'speaker': 46, 'enable_interrogative_upspeak': True})
    request = requests.post(f'{voicevox_url}/synthesis?{params_encoded}', json=request.json())

    with open("test.wav", "wb") as outfile:
        outfile.write(request.content)

if __name__ == "__main__":
    silero_tts()
`

**Comment by OkoTale** [comment]
here's my tts 

```
import os
import torch
import requests
import urllib.parse
from utils.katakana import *

# https://github.com/snakers4/silero-models#text-to-speech
def silero_tts(tts, language, model, speaker):
    device = torch.device('cpu')
    torch.set_num_threads(4)
    local_file = 'model.pt'

    if not os.path.isfile(local_file):
        torch.hub.download_url_to_file(f'https://models.silero.ai/models/tts/{language}/{model}.pt',
                                    local_file)  

    model = torch.package.PackageImporter(local_file).load_pickle("tts_models", "model")
    model.to(device)

    example_text = "i'm fine thank you and you?"
    sample_rate = 48000

    audio_paths = model.save_wav(text=tts,
                                speaker=speaker,
                                sample_rate=sample_rate)
    
def voicevox_tts(tts):
    # You need to run VoicevoxEngine.exe first before running this script
    
    voicevox_url = 'http://localhost:50021'
    # Convert the text to katakana. Example: ORANGE -> オレンジ, so the voice will sound more natural
    katakana_text = katakana_converter(tts)
    # You can change the voice to your liking. You can find the list of voices on speaker.json
    # or check the website https://voicevox.hiroshiba.jp
    params_encoded = urllib.parse.urlencode({'text': katakana_text, 'speaker': 46})
    request = requests.post(f'{voicevox_url}/audio_query?{params_encoded}')
    params_encoded = urllib.parse.urlencode({'speaker': 46, 'enable_interrogative_upspeak': True})
    request = requests.post(f'{voicevox_url}/synthesis?{params_encoded}', json=request.json())

    with open("test.wav", "wb") as outfile:
        outfile.write(request.content)

if __name__ == "__main__":
    silero_tts()
```
