### ISSUE TITLE
subtitles!

### ISSUE THREAD

**Issue by b-e-y** [ardha27/AI-Waifu-Vtuber#6]
how to remove indonesian subtitles and use english subtitles ?

**Comment by ardha27** [comment]
the most simple way is to change this line

result_id = translate_google(text, "EN", "ID")

into

result_id = text

----
text is the answer in EN
the translate_google(text, "EN", "ID") function is translating the answer from EN to ID

**Comment by b-e-y** [comment]
thansk, it works now!
