### ISSUE TITLE
Elevenlab

### ISSUE THREAD

**Issue by W4RI0CK** [ardha27/AI-Waifu-Vtuber#60]
Hello,  would it be possible to use Elevenlab voices?
Here are the APIs https://api.elevenlabs.io/docs#/

possibly the eleven_multilingual_v1 version to be able to use multiple different languages.

**Comment by ardha27** [comment]
Yes you can add TTS api as long as you knoe how to use the API

**Comment by W4RI0CK** [comment]
this is the problem, i don't know how to do it 😒

**Comment by ardha27** [comment]
Than learn how to use it
