### ISSUE TITLE
Silero Lenguages not working

### ISSUE THREAD

**Issue by SonixOmega** [ardha27/AI-Waifu-Vtuber#88]
I have this issue:

silero_tts:
![image](https://github.com/ardha27/AI-Waifu-Vtuber/assets/124184924/6ba3acff-bc2b-40af-95d3-64c085ea01d2)

Error:
![image](https://github.com/ardha27/AI-Waifu-Vtuber/assets/124184924/99baff1d-b922-4b87-927d-9d8d248f6dc7)

**Comment by ardha27** [comment]
Delete first the currrent model pth file

**Comment by SonixOmega** [comment]
Forgive me, but I'm new to python and I don't really know what you mean, could you explain it to me in more detail please? @ardha27

**Comment by ardha27** [comment]
You should found model.pt on your folder, delete it and run again your code

**Comment by SonixOmega** [comment]
Ohhhh now it works, thank you :D
